spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.password-reset.expiration-minutes=${RESET_EXPIRATION_MINUTES}
app.frontend.reset-password-url=${FRONTEND_RESET_URL}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

app.storage.bucket=${BUCKET}
app.storage.endpoint=${ENDPOINT}
app.storage.region=${REGION}
app.storage.access-key=${ACCESS_KEY_ID}
app.storage.secret-key=${SECRET_ACCESS_KEY}
app.storage.presign-expiration-minutes=60